'use client';
import {useState} from 'react';
const money=n=>'₱'+Number(n).toLocaleString('en-PH',{minimumFractionDigits:2});
const menu=['Dashboard','Projects','BOQ / Estimates','Job Costing','Billing','Collections','Purchases','Materials','Payroll','Customers','Suppliers','Reports'];
const projects=[{name:'Del Rosario Residence',client:'Del Rosario',contract:4850000,cost:3015000,status:'Active'},{name:'Santos Residence',client:'Santos',contract:3200000,cost:1980000,status:'Active'},{name:'Garcia Renovation',client:'Garcia',contract:1250000,cost:810000,status:'Completed'}];
export default function Home(){const [tab,setTab]=useState('Dashboard');return <div><header style={{background:'#173f2a',color:'white',padding:'18px 24px'}}><b style={{fontSize:22}}>ISIDRO BUILDMASTERS</b><div>Cloud Accounting & Construction Management</div></header><div style={{display:'flex',minHeight:'calc(100vh - 82px)'}}><aside style={{width:220,background:'#fff',padding:12}}>{menu.map(m=><button key={m} onClick={()=>setTab(m)} style={{display:'block',width:'100%',textAlign:'left',padding:12,border:0,background:tab===m?'#e9f2ec':'transparent',borderRadius:7,marginBottom:4,cursor:'pointer'}}>{m}</button>)}</aside><main style={{padding:28,flex:1,maxWidth:1200}}><h2>{tab}</h2>{tab==='Dashboard'&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:14}}>{[['Total Contracts',9300000],['Project Costs',5805000],['Total Billed',1250000],['Collections',830000],['Receivables',420000],['Estimated Profit',3495000]].map(x=><div key={x[0]} style={{background:'#fff',padding:18,borderRadius:10,boxShadow:'0 1px 4px #ddd'}}><small>{x[0]}</small><div style={{fontSize:24,fontWeight:700,marginTop:7}}>{money(x[1])}</div></div>)}</div><h3 style={{marginTop:30}}>Projects</h3><Table rows={projects}/></>}{tab==='Projects'&&<><button style={btn}>+ New Project</button><Table rows={projects}/></>}{tab==='BOQ / Estimates'&&<Module text="Create estimates by category, quantity, materials, labor, equipment and markup."/>}{tab==='Job Costing'&&<Module text="Record actual materials, labor, equipment and other costs against each project."/>}{tab==='Billing'&&<Module text="Create progress billings linked to contracts and track percentage billed."/>}{tab==='Collections'&&<Module text="Record customer collections and automatically reduce accounts receivable."/>}{['Purchases','Materials','Payroll','Customers','Suppliers','Reports'].includes(tab)&&<Module text={`${tab} module is ready for connection to the Isidro1 cloud database.`}/>}</main></div></div>}
function Module({text}){return <><button style={btn}>+ Add Entry</button><div style={{background:'#fff',padding:20,marginTop:16,borderRadius:10}}>{text}</div></>}
function Table({rows}){return <table style={{width:'100%',background:'#fff',borderCollapse:'collapse',marginTop:16}}><thead><tr>{['Project','Client','Contract','Cost','Profit','Status'].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.name}>{[p.name,p.client,money(p.contract),money(p.cost),money(p.contract-p.cost),p.status].map((x,i)=><td key={i} style={td}>{x}</td>)}</tr>)}</tbody></table>}
const btn={background:'#173f2a',color:'#fff',border:0,borderRadius:7,padding:'11px 15px',cursor:'pointer'};const th={padding:11,textAlign:'left',borderBottom:'1px solid #ddd'};const td={padding:11,borderBottom:'1px solid #eee'};
